const loremParagraphs = [
  `Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero provident quod excepturi, illum magnam quam minima laudantium distinctio repellat nihil culpa eum tempora officia possimus. Recusandae eveniet voluptas harum architecto nam beatae, temporibus soluta deleniti pariatur neque aliquam animi est suscipit ab atque debitis repellendus voluptatum? Id quod doloremque dolorem?`,
  `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse reprehenderit dolore dolores vero soluta vitae corrupti explicabo similique modi, a velit officia deserunt aspernatur sapiente? Voluptates voluptas beatae ratione sunt hic molestias vero corrupti, odit assumenda maiores eaque, aperiam temporibus officia eveniet! Neque, quis animi doloremque maiores est expedita atque?`,
  `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit nisi deleniti blanditiis est veritatis molestiae, iure, enim repudiandae hic laudantium delectus possimus earum repellat ad beatae, omnis nihil obcaecati. Quas, assumenda tempore! Debitis error cum ullam eveniet a ducimus, porro fugit consequuntur et? Quod voluptas, natus dolore officiis consectetur officia?`,
  `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus, numquam laborum aut aliquam adipisci dolores fugiat provident porro animi dolor, magnam doloremque sint praesentium, quisquam quasi commodi nostrum! Earum, eos! Et doloremque incidunt earum, quod corporis tempore? Quae laudantium sed, expedita blanditiis autem aliquam quisquam. Assumenda nisi consequuntur aliquam doloribus!`,
  `Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam culpa dolor nihil et neque nisi sequi magni rem nemo vero unde harum voluptate explicabo recusandae delectus repellendus minus ratione, praesentium iste quo illum odit officia possimus. Unde asperiores eveniet nisi omnis optio veritatis officiis maxime, tempora voluptatem est, assumenda eius?`,
  `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptatibus odit aut iusto perspiciatis molestiae maiores voluptatem. Assumenda laudantium nostrum cupiditate accusantium esse natus nobis adipisci, eius, modi minus vero amet quisquam vitae ab tenetur qui. Inventore architecto, consequuntur vitae laudantium exercitationem similique earum voluptatum porro sequi temporibus vero repellendus!`,
  `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora quaerat perspiciatis quas doloribus magnam provident quasi accusantium cupiditate dolor. In modi nostrum neque itaque pariatur dolorum, eaque tempore doloribus optio at illo minus vero saepe, debitis illum fuga adipisci animi iste ipsa quaerat aut. Totam magni eligendi ipsa ipsam vitae.`,
  `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Excepturi quia mollitia nobis quod sequi maiores laboriosam nesciunt sint et necessitatibus, delectus impedit commodi? Dolore dolorem sed iste iure animi tempora? Magni, voluptatum et. Blanditiis optio, fuga similique harum ea cumque. At perferendis fugit quaerat? Fugit possimus ex vero rem delectus.`,
  `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde dolorem quasi sequi, temporibus ratione quam illum dolor tenetur. Temporibus voluptas, eos nostrum eveniet voluptate repudiandae ex eligendi deleniti quis obcaecati, assumenda voluptatem ea fugiat veniam! Vero natus deleniti fugiat cumque, culpa libero vitae nam architecto ab iste dolores ratione officiis?`,
  `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut quas magni vero voluptas natus quo eveniet, vel reprehenderit tempora maiores quos quibusdam doloremque ratione hic officia optio eos nesciunt possimus accusantium itaque dolores odio? Dolore, iusto! Blanditiis quibusdam temporibus doloribus officia culpa, possimus optio deleniti libero expedita voluptatum, voluptatibus minus?`,
];

export default loremParagraphs;
